title: Teklid
subtitle: Teklid
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site
author: JÃ©rÃ©my Toussaint
email: jeremy@toussaint.dev
avatar: assets/images/avatar.jpg
